spring:
  security:
    cors:
      pathPattern: "/bff/**"
      allow-credentials: true
      allowed-headers:
        - "*"
      allowed-methods: [GET, POST, PUT, DELETE]
      allowed-origins:
        - "*"
      exposed-headers:
        - "*"
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/.well-known/jwks.json
          issuer-uri: http://localhost:8000
    user:
      name: user
      password: 1234
      roles:
        - ADMIN