spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/.well-known/jwks.json
          issuer-uri: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus