name: Compile and test
run-name: Compile and test ${{ github.actor }}
on: [push]
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Check if OpenAPI JSON is up to date
        run: |
          if git diff --quiet HEAD -- docs/openapi.json; then
            echo "The file 'docs/openapi.json' is up to date."
          else
            echo "The file 'docs/openapi.json' is not up to date. You should run mvn verify locally and commit the file."
            exit 1
          fi
